;;; start package
(setq gc-cons-threshold (* 50 1000 1000))
(setq gc-cons-percentage 0.6)
(add-to-list 'load-path "~/emacs-loads")
(require 'my-settings)
(require 'my-packages)
(require 'my-scripts)
(require 'my-keys)
(require 'my-style)
(require 'my-autocomplete)
;; (require 'my-vertico)
;; (require 'my-ivy)
(require 'my-helm)
;; (require 'my-spell)
(require 'my-org)
(require 'my-projectile)
(require 'my-flycheck)
(require 'my-lsp)
(require 'my-dap)
;; ;; (require 'my-yasnippet)
(require 'my-programming)
(require 'my-web)
(require 'my-js)
;; (require 'my-pascal)
(require 'my-dart)
(require 'my-python)
;; (require 'my-php)
(require 'my-go)

(setq gc-cons-threshold (* 2 1000 1000))

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   '("8721f7ee8cd0c2e56d23f757b44c39c249a58c60d33194fe546659dabc69eebd" default))
 '(package-selected-packages
   '(emojify dap-mode dart-server flycheck lsp-python-ms flymake-python-pyflakes consult orderless vertico smex helm-lsp company-box esup company-lsp yasnippet-snippets yasnippet-classic-snippets yaml-mode xml-format which-key web-mode vue-mode use-package tide terraform-mode tern swift3-mode slime rjsx-mode redis rainbow-delimiters python-mode projectile prettier-js powershell plantuml-mode phps-mode org-bullets ob-sql-mode ob-redis ob-powershell ob-php ob-go multi-web-mode magit lsp-ui lsp-julia lsp-dart json-mode js2-refactor js-doc helm go-snippets go-mode git-timemachine frame-local flymake-php fic-mode erlang elpy elixir-mode dumb-jump dracula-theme dotenv-mode dockerfile-mode django-snippets csharp-mode company-solidity company-quickhelp company-prescient company-php cider better-defaults angular-mode ac-php)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
